   # frontend/Dockerfile
   # Node.js 18 알파인 이미지를 빌더 스테이지의 베이스로 사용
   FROM node:18-alpine AS builder
   
   # 작업 디렉토리를 /app으로 설정
   WORKDIR /app
   
   # package.json과 package-lock.json 파일을 컨테이너로 복사
   COPY package.json package-lock.json ./
   # 프로젝트 종속성 설치
   RUN npm install
   
   # 빌드 캐시를 무시하는 인자
   ARG CACHEBUST

   # 현재 디렉토리의 모든 파일을 컨테이너로 복사
   COPY . .
   # Next.js 프로젝트 빌드 실행
   RUN npm run build
   
   # 실행 환경을 위한 새로운 스테이지 시작
   FROM node:18-alpine AS runner
   
   # 실행 환경의 작업 디렉토리 설정
   WORKDIR /app
   
   # 빌드된 파일들을 빌더 스테이지에서 실행 환경으로 복사
   COPY --from=builder /app/next.config.ts ./
   COPY --from=builder /app/public ./public
   COPY --from=builder /app/.next ./.next
   COPY --from=builder /app/node_modules ./node_modules
   COPY --from=builder /app/package.json ./package.json
   
   # 3000번 포트 노출
   EXPOSE 3000
   
   # 애플리케이션 실행 명령어
   CMD ["npm", "start"]