version: "3"

services:
  photoprism:
    image: photoprism/photoprism
    restart: unless-stopped
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "1234"
      PHOTOPRISM_UPLOAD_NSFW: "false"
    volumes:
      - ./photos:/photoprism/originals
      - ./photoprism-storage:/photoprism/storage
    networks:
      - photoprism-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON_URL: http://localhost:2342/api/v1/swagger.json
      CORS: "*"
      SWAGGER_UI_CORS: "true"
    depends_on:
      - photoprism
    networks:
      - photoprism-network

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - photoprism
    networks:
      - photoprism-network

networks:
  photoprism-network:
    driver: bridge
