services:
  photoprism:
    image: photoprism/photoprism
    restart: unless-stopped
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_SITE_URL: "https://sonapokets.day/admin" # base URL 설정
      PHOTOPRISM_SITE_PATH: "/admin" # 기본 경로 설정
      PHOTOPRISM_UPLOAD_NSFW: "false"
      PHOTOPRISM_API_ENABLED: "true"
    volumes:
      - ./photos:/photoprism/originals
      - ./photoprism-storage:/photoprism/storage
    networks:
      - photoprism-network

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - photoprism
    networks:
      - photoprism-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - photoprism-network
    depends_on:
      - nginx

networks:
  photoprism-network:
    driver: bridge
