version: "3"

services:
  photoprism:
    image: photoprism/photoprism
    restart: unless-stopped
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}"
      PHOTOPRISM_UPLOAD_NSFW: "false"
      PHOTOPRISM_API_ENABLED: "true"
      PHOTOPRISM_API_DOCS: "true"
    volumes:
      - ./photos:/photoprism/originals
      - ./photoprism-storage:/photoprism/storage
    networks:
      - photoprism-network

  swagger-generator:
    image: photoprism/photoprism
    command: make swag && make build && ./photoprism start
    volumes:
      - ./photos:/photoprism/originals
      - ./photoprism-storage:/photoprism/storage
    networks:
      - photoprism-network
    depends_on:
      - photoprism

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON_URL: https://sonapokets.day/admin/api/v1/swagger.json
      CORS: "*"
      SWAGGER_UI_CORS: "true"
      # 추가 설정
      SERVER_URL: "https://sonapokets.day"
    depends_on:
      - photoprism
    networks:
      - photoprism-network

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - photoprism
    networks:
      - photoprism-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=https://sonapokets.day/admin/api/v1
    networks:
      - photoprism-network
    depends_on:
      - photoprism
networks:
  photoprism-network:
    driver: bridge
