name: Deploy sonapokets

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Pull latest code
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} "cd ~/github/sonapokets && git pull"

      - name: Start Nginx service first
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} "cd ~/github/sonapokets && docker-compose up -d nginx"

      - name: Wait for Nginx to start
        run: |
          echo "Waiting for Nginx to start..."
          sleep 10

      - name: Start PhotoPrism service
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} "cd ~/github/sonapokets && docker-compose up -d photoprism"

      - name: Wait for PhotoPrism to start
        run: |
          echo "Waiting for PhotoPrism to start..."
          sleep 30

      - name: Build and start Frontend service
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} "cd ~/github/sonapokets && docker-compose build frontend --build-arg CACHEBUST=$(date +%s) && docker-compose up -d frontend"

      - name: Wait for Frontend to start
        run: |
          echo "Waiting for Frontend to start..."
          sleep 10

      - name: Restart Nginx to ensure proper connectivity
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} "cd ~/github/sonapokets && docker-compose restart nginx"

      - name: Deployment completed
        run: |
          echo "Deployment completed successfully!"
